In [46]:
from flask import Flask, jsonify
from pymongo import MongoClient
from flask_cors import CORS
from flask import render_template
import numpy as np
from datetime import datetime

In [47]:
connection_string = "mongodb://bird:bird@ac-yaj6jma-shard-00-00.yombdgz.mongodb.net:27017,ac-yaj6jma-shard-00-01.yombdgz.mongodb.net:27017,ac-yaj6jma-shard-00-02.yombdgz.mongodb.net:27017/?replicaSet=atlas-pjw3c3-shard-0&ssl=true&authSource=admin"
client = MongoClient(connection_string)
db = client['bird_db']

In [43]:
# Fetching data from collections
flamingos = list(db['filtered_flamingo'].find({}, {'_id': False}))
hummingbirds = list(db['filtered_hummingbird'].find({}, {'_id': False}))
owls = list(db['filtered_owl'].find({}, {'_id': False}))
teals = list(db['filtered_teal'].find({}, {'_id': False}))
band_type = list(db['band_type'].find({}, {'_id': False, 'band_type': True}))
event_type = list(db['event_type'].find({}, {'_id': False, 'event_type': True}))
country_state = list(db['country_state'].find({}, {'_id': False, 'country_state': True}))
sex = list(db['sex'].find({}, {'_id': False, 'sex': True}))
species = list(db['species'].find({}, {'_id': False, 'species': True}))


In [48]:
print(len(flamingos))

['American Flamingo']
3718


In [4]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('../data/filtered/filtered_flamingo.csv')

# Check the length of the CSV file
length = len(df)

print(f"The length of the CSV file is: {length} rows")


The length of the CSV file is: 1859 rows


In [36]:
client.close()

In [ ]:
# make lists of each csv

In [5]:
filtered_flamingo = pd.read_csv('../data/filtered/filtered_flamingo.csv')
filtered_hummingbird = pd.read_csv('../data/filtered/filtered_hummingbird.csv')
filtered_owl = pd.read_csv('../data/filtered/filtered_owl.csv')
filtered_teal = pd.read_csv('../data/filtered/filtered_teal.csv')

C:\Users\Jared\AppData\Local\Temp\ipykernel_11520\339202248.py:4: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  filtered_teal = pd.read_csv('../data/filtered/filtered_teal.csv')


In [7]:
# Change LONGITUDE to LON_DD for teal
filtered_teal = filtered_teal.rename(columns={'LONGITUDE': 'LON_DD'})
# Change LATITUDE to LAT_DD for teal
filtered_teal = filtered_teal.rename(columns={'LATITUDE': 'LAT_DD'})

In [11]:
# remove rows that have "nan" values
filtered_flamingo = filtered_flamingo.dropna()
filtered_hummingbird = filtered_hummingbird.dropna()
filtered_owl = filtered_owl.dropna()
filtered_teal = filtered_teal.dropna()

In [9]:
# filter df by event_year from highest to lowest
filtered_flamingo = filtered_flamingo.sort_values(by=['EVENT_YEAR'], ascending=False)
filtered_hummingbird = filtered_hummingbird.sort_values(by=['EVENT_YEAR'], ascending=False)
filtered_owl = filtered_owl.sort_values(by=['EVENT_YEAR'], ascending=False)
filtered_teal = filtered_teal.sort_values(by=['EVENT_YEAR'], ascending=False)

In [20]:
# print unique event_year
print(filtered_flamingo['EVENT_YEAR'].unique())
# print the number of 2015, 1970, 1968, 1964 event_year
print(len(filtered_flamingo[filtered_flamingo['EVENT_YEAR'] == 2015]))
print(len(filtered_flamingo[filtered_flamingo['EVENT_YEAR'] == 1970]))
print(len(filtered_flamingo[filtered_flamingo['EVENT_YEAR'] == 1968]))
print(len(filtered_flamingo[filtered_flamingo['EVENT_YEAR'] == 1964]))

[2015 1970 1968 1964]
1
976
747
99


In [27]:
# make a new df with 1 entry of 2015, 450 entries of 1970, 450 entries of 1968, 99 entries of 1964
updated_flamingo = pd.concat([filtered_flamingo[filtered_flamingo['EVENT_YEAR'] == 2015],
                                filtered_flamingo[filtered_flamingo['EVENT_YEAR'] == 1970].head(450),
                                filtered_flamingo[filtered_flamingo['EVENT_YEAR'] == 1968].head(450),
                                filtered_flamingo[filtered_flamingo['EVENT_YEAR'] == 1964].head(99)])
# save df to csv in data/filtered/Updated_Filtered_leq_1000
updated_flamingo.to_csv('../data/filtered/Updated_Filtered_leq_1000/updated_flamingo.csv', index=False)

In [25]:
# print unique event_year for hummingbird
print(filtered_hummingbird['EVENT_YEAR'].unique())
# print the number of 2020, 2014, 1965, 1960 event_year for hummingbird
print(len(filtered_hummingbird[filtered_hummingbird['EVENT_YEAR'] == 2020]))
print(len(filtered_hummingbird[filtered_hummingbird['EVENT_YEAR'] == 2014]))
print(len(filtered_hummingbird[filtered_hummingbird['EVENT_YEAR'] == 1965]))
print(len(filtered_hummingbird[filtered_hummingbird['EVENT_YEAR'] == 1960]))

[2020 2019 2018 2017 2016 2015 2014 1965 1964 1963 1962 1961 1960]
17245
20948
481
154


In [26]:
# make a new df with 150 entry of 2020, 350 entries of 2014, 350 entries of 1965, 150 entries of 1960
updated_hummingbird = pd.concat([filtered_hummingbird[filtered_hummingbird['EVENT_YEAR'] == 2020].head(150),
                                filtered_hummingbird[filtered_hummingbird['EVENT_YEAR'] == 2014].head(350),
                                filtered_hummingbird[filtered_hummingbird['EVENT_YEAR'] == 1965].head(350),
                                filtered_hummingbird[filtered_hummingbird['EVENT_YEAR'] == 1960].head(150)])
# save df to csv in data/filtered/Updated_Filtered_leq_1000
updated_hummingbird.to_csv('../data/filtered/Updated_Filtered_leq_1000/updated_hummingbird.csv', index=False)

In [29]:
# print unique event_year for owl
print(filtered_owl['EVENT_YEAR'].unique())
# print the number of 2020, 2014, 1965, 1960 event_year for owl
print(len(filtered_owl[filtered_owl['EVENT_YEAR'] == 2020]))
print(len(filtered_owl[filtered_owl['EVENT_YEAR'] == 2014]))
print(len(filtered_owl[filtered_owl['EVENT_YEAR'] == 1965]))
print(len(filtered_owl[filtered_owl['EVENT_YEAR'] == 1960]))

[2020 2019 2018 2017 2016 2015 2014 1965 1964 1963 1962 1961 1960]
17264
12937
564
173


In [30]:
# make a new df with 150 entry of 2020, 350 entries of 2014, 350 entries of 1965, 150 entries of 1960
updated_owl = pd.concat([filtered_owl[filtered_owl['EVENT_YEAR'] == 2020].head(150),
                                filtered_owl[filtered_owl['EVENT_YEAR'] == 2014].head(350),
                                filtered_owl[filtered_owl['EVENT_YEAR'] == 1965].head(350),
                                filtered_owl[filtered_owl['EVENT_YEAR'] == 1960].head(150)])
# save df to csv in data/filtered/Updated_Filtered_leq_1000
updated_owl.to_csv('../data/filtered/Updated_Filtered_leq_1000/updated_owl.csv', index=False)

In [32]:
# print unique event_year for teal
print(filtered_teal['EVENT_YEAR'].unique())
# print the number of 2020, 2014, 1965, 1960 event_year for teal
print(len(filtered_teal[filtered_teal['EVENT_YEAR'] == 2020]))
print(len(filtered_teal[filtered_teal['EVENT_YEAR'] == 2014]))
print(len(filtered_teal[filtered_teal['EVENT_YEAR'] == 1965]))
print(len(filtered_teal[filtered_teal['EVENT_YEAR'] == 1960]))

[2020 2019 2018 2017 2016 2015 2014 1965 1964 1963 1962 1961 1960]
2646
9707
27288
6666


In [33]:
# make a new df with 150 entry of 2020, 350 entries of 2014, 350 entries of 1965, 150 entries of 1960
updated_teal = pd.concat([filtered_teal[filtered_teal['EVENT_YEAR'] == 2020].head(150),
                                filtered_teal[filtered_teal['EVENT_YEAR'] == 2014].head(350),
                                filtered_teal[filtered_teal['EVENT_YEAR'] == 1965].head(350),
                                filtered_teal[filtered_teal['EVENT_YEAR'] == 1960].head(150)])
# save df to csv in data/filtered/Updated_Filtered_leq_1000
updated_teal.to_csv('../data/filtered/Updated_Filtered_leq_1000/updated_teal.csv', index=False)

In [40]:
# convert the 4 updated_filtered csv to list of dictionaries
updated_flamingo_dict = updated_flamingo.to_dict('records')
updated_hummingbird_dict = updated_hummingbird.to_dict('records')
updated_owl_dict = updated_owl.to_dict('records')
updated_teal_dict = updated_teal.to_dict('records')

# print first 5 rows of updated_flamingo_dict
print(updated_flamingo_dict[:5])

# convert the 4 dictionaries to json
import json
# save the 4 json files to data/filtered/Updated_Filtered_leq_1000/json
with open('../data/filtered/Updated_Filtered_leq_1000/json/updated_flamingo.json', 'w') as f:
    json.dump(updated_flamingo_dict, f)
with open('../data/filtered/Updated_Filtered_leq_1000/json/updated_hummingbird.json', 'w') as f:
    json.dump(updated_hummingbird_dict, f)
with open('../data/filtered/Updated_Filtered_leq_1000/json/updated_owl.json', 'w') as f:
    json.dump(updated_owl_dict, f)
with open('../data/filtered/Updated_Filtered_leq_1000/json/updated_teal.json', 'w') as f:
    json.dump(updated_teal_dict, f)

[{'BAND': 'B28809270040', 'ORIGINAL_BAND': 'B28809270040', 'EVENT_TYPE': 'B', 'EVENT_DATE': '10/20/2015', 'EVENT_YEAR': 2015, 'ISO_COUNTRY': 'US', 'LAT_DD': 25.15833, 'LON_DD': -80.88583, 'CP': 0.0, 'BAND_TYPE': 41, 'SPECIES_ID': 1820, 'BIRD_STATUS': 2.0, 'AGE_CODE': 1.0, 'SEX_CODE': 0.0, 'SPECIES_NAME': 'American Flamingo', 'SCIENTIFIC_NAME': 'Phoenicopterus ruber', 'AGE_DESCRIPTION': 'After Hatching Year', 'SEX_DESCRIPTION': 'Unknown'}, {'BAND': 'B39339745784', 'ORIGINAL_BAND': 'B39339745784', 'EVENT_TYPE': 'B', 'EVENT_DATE': '06/06/1970', 'EVENT_YEAR': 1970, 'ISO_COUNTRY': 'BS', 'LAT_DD': 21.08333, 'LON_DD': -73.41667, 'CP': 10.0, 'BAND_TYPE': 12, 'SPECIES_ID': 1820, 'BIRD_STATUS': 3.0, 'AGE_CODE': 4.0, 'SEX_CODE': 0.0, 'SPECIES_NAME': 'American Flamingo', 'SCIENTIFIC_NAME': 'Phoenicopterus ruber', 'AGE_DESCRIPTION': 'Local', 'SEX_DESCRIPTION': 'Unknown'}, {'BAND': 'B49339749659', 'ORIGINAL_BAND': 'B49339749659', 'EVENT_TYPE': 'B', 'EVENT_DATE': '06/07/1970', 'EVENT_YEAR': 1970, 'IS

In [41]:
# unique "SPECIES_NAME" for each species
print(updated_flamingo['SPECIES_NAME'].unique())
print(updated_hummingbird['SPECIES_NAME'].unique())
print(updated_owl['SPECIES_NAME'].unique())
print(updated_teal['SPECIES_NAME'].unique())

['American Flamingo']
['Ruby-throated Hummingbird']
['Northern Saw-whet Owl']
['Blue-winged Teal']


In [43]:
# print dtype of event_date
print(updated_flamingo['EVENT_DATE'].dtype)
# print first 5 rows of event_date
print(updated_flamingo['EVENT_DATE'].head())

object
0       10/20/2015
924     06/06/1970
1233    06/07/1970
1231    06/07/1970
1230    06/07/1970
Name: EVENT_DATE, dtype: object


In [48]:
# Name of the collection you want to update
collection_name = "filtered_flamingo"
collection = db[collection_name]

# Iterate through the documents in the collection
for doc in collection.find():
    # Convert the 'event_date' string to a datetime object
    event_date = datetime.strptime(doc['EVENT_DATE'], '%m/%d/%Y')
    
    # Update the document with the new datetime object
    collection.update_one({'_id': doc['_id']}, {'$set': {'EVENT_DATE': event_date}})

# Name of the collection you want to update
collection_name = "filtered_hummingbird"
collection = db[collection_name]

# Iterate through the documents in the collection
for doc in collection.find():
    # Convert the 'event_date' string to a datetime object
    event_date = datetime.strptime(doc['EVENT_DATE'], '%m/%d/%Y')
    
    # Update the document with the new datetime object
    collection.update_one({'_id': doc['_id']}, {'$set': {'EVENT_DATE': event_date}})
# Name of the collection you want to update
collection_name = "filtered_owl"
collection = db[collection_name]

# Iterate through the documents in the collection
for doc in collection.find():
    # Convert the 'event_date' string to a datetime object
    event_date = datetime.strptime(doc['EVENT_DATE'], '%m/%d/%Y')
    
    # Update the document with the new datetime object
    collection.update_one({'_id': doc['_id']}, {'$set': {'EVENT_DATE': event_date}})

# Name of the collection you want to update
collection_name = "filtered_teal"
collection = db[collection_name]

# Iterate through the documents in the collection
for doc in collection.find():
    # Convert the 'event_date' string to a datetime object
    event_date = datetime.strptime(doc['EVENT_DATE'], '%m/%d/%Y')
    
    # Update the document with the new datetime object
    collection.update_one({'_id': doc['_id']}, {'$set': {'EVENT_DATE': event_date}})


In [49]:
# Name of the collection you want to check
collection_name = "filtered_flamingo"
collection = db[collection_name]

# 1. Count the number of documents with the updated format
count_datetime_format = collection.count_documents({'EVENT_DATE': {'$type': 'date'}})
total_documents = collection.count_documents({})

print(f"Number of documents with datetime format: {count_datetime_format}")
print(f"Total number of documents: {total_documents}")

# 2. Randomly sample some documents
sample_docs = collection.aggregate([{'$sample': {'size': 5}}])

for doc in sample_docs:
    print(doc['EVENT_DATE'])

# Check if all documents have been updated
if count_datetime_format == total_documents:
    print("Update was successful!")
else:
    print("Update was not fully successful. Some documents might not have been updated.")


Number of documents with datetime format: 1000
Total number of documents: 1000
1970-06-07 00:00:00
1968-07-27 00:00:00
1970-06-06 00:00:00
1970-06-07 00:00:00
1970-06-06 00:00:00
Update was successful!


In [34]:
# convert all csv files in data/filtered/Updated_Filtered_leq_1000 to json files in data/filtered/Updated_Filtered_leq_1000/json
import csv
import json

csv_file = '../data/filtered/Updated_Filtered_leq_1000/updated_flamingo.csv'
json_file = '../data/filtered/Updated_Filtered_leq_1000/json/updated_flamingo.json'

with open(csv_file) as f:
    reader = csv.DictReader(f)
    rows = list(reader)

with open(json_file, 'w') as f:
    json.dump(rows, f)

csv_file = '../data/filtered/Updated_Filtered_leq_1000/updated_hummingbird.csv'
json_file = '../data/filtered/Updated_Filtered_leq_1000/json/updated_hummingbird.json'

with open(csv_file) as f:
    reader = csv.DictReader(f)
    rows = list(reader)

with open(json_file, 'w') as f:
    json.dump(rows, f)

csv_file = '../data/filtered/Updated_Filtered_leq_1000/updated_owl.csv'
json_file = '../data/filtered/Updated_Filtered_leq_1000/json/updated_owl.json'

with open(csv_file) as f:
    reader = csv.DictReader(f)
    rows = list(reader)

with open(json_file, 'w') as f:
    json.dump(rows, f)

csv_file = '../data/filtered/Updated_Filtered_leq_1000/updated_teal.csv'
json_file = '../data/filtered/Updated_Filtered_leq_1000/json/updated_teal.json'

with open(csv_file) as f:
    reader = csv.DictReader(f)
    rows = list(reader)

with open(json_file, 'w') as f:
    json.dump(rows, f)

# confirm that the json files are created
import os
print(os.listdir('../data/filtered/Updated_Filtered_leq_1000/json'))

['updated_flamingo.json', 'updated_hummingbird.json', 'updated_owl.json', 'updated_teal.json']
